# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $TABLE_WISE_DATABASE_PASSWORD
      POSTGRES_USER: $TABLE_WISE_DATABASE_USER
      POSTGRES_DB: $TABLE_WISE_DATABASE_NAME

  table-wise:
    env_file:
      - .env
    
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - TABLE_WISE_DATABASE_NAME=${TABLE_WISE_DATABASE_NAME}
      - TABLE_WISE_DATABASE_USER=${TABLE_WISE_DATABASE_USER}
      - TABLE_WISE_DATABASE_PASSWORD=${TABLE_WISE_DATABASE_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
      - ./app:/rails/app
    depends_on:
      - db
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data: {}
  app-storage: {}